int sensorPin = A0;    // select the input pin for the potentiometer
int ledPin = 13;      // select the pin for the LED
int sensorValue = 0;  // variable to store the value coming from the sensor
long randomNumber;    //this variable will hold a random number generated by the random() function
int led = 13;

void setup() {
  // declare the ledPin as an OUTPUT:
  pinMode(led, OUTPUT);
  randomSeed(42);
}

void loop() {
  //generate a random number:
  randomNumber = random(2,5);
  // read the value from the sensor:
  sensorValue = analogRead(sensorPin);
  // turn the led on
  digitalWrite(led, HIGH);
  // stop the program for <sensorValue> milliseconds:
  delay(sensorValue);
  // turn the led off:
  digitalWrite(led, LOW);
  // stop the program for for <sensorValue> milliseconds:
  delay(sensorValue);
  //Prints the sensor value:
  Serial.println(sensorValue);
 
  delay(1);
}
